"""empty message

Revision ID: 94934f5fc47b
Revises: 91f6b26fc22e
Create Date: 2020-08-13 23:09:56.951158

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '94934f5fc47b'
down_revision = '91f6b26fc22e'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('Shows', 'artist_id',
               existing_type=sa.INTEGER(),
               nullable=False)
    op.alter_column('Shows', 'venue_id',
               existing_type=sa.INTEGER(),
               nullable=False)
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('Shows', 'venue_id',
               existing_type=sa.INTEGER(),
               nullable=True)
    op.alter_column('Shows', 'artist_id',
               existing_type=sa.INTEGER(),
               nullable=True)
    # ### end Alembic commands ###
