"""empty message

Revision ID: cf8cd7515a78
Revises: 8d932ccf77c5
Create Date: 2020-08-10 22:39:38.037218

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision = 'cf8cd7515a78'
down_revision = '8d932ccf77c5'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('Shows', sa.Column('start_time', sa.DateTime(), nullable=True))
    op.drop_column('Shows', 'starter_time')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('Shows', sa.Column('starter_time', postgresql.TIMESTAMP(), autoincrement=False, nullable=True))
    op.drop_column('Shows', 'start_time')
    # ### end Alembic commands ###
